"""Writer agent: drafts the comprehensive research report."""

from langchain_core.messages import HumanMessage, SystemMessage

from app.config import get_settings
from app.prompts.writer import WRITER_SYSTEM
from app.services.llm import get_chat_model


def _fallback_report(payload: dict) -> str:
    request = payload["user_request"]
    lines = [
        f"# Research Report: {request[:80]}",
        "",
        "## Executive Summary",
        "- Pipeline ran end-to-end (no LLM credentials; generated by fallback writer).",
        "- Findings and analysis artifacts below are from the research/analysis stages.",
        "",
        "## Findings",
    ]
    research = payload.get("research_results") or []
    sources = payload.get("research_sources") or []
    if research:
        for idx, item in enumerate(research, 1):
            lines.append(f"### Finding {idx}")
            lines.append(str(item)[:1500])
    else:
        lines.append("No research findings were produced.")

    lines.extend(["", "## Data Analysis"])
    analysis = payload.get("analysis_output") or ""
    analysis_result = payload.get("analysis_result")
    if analysis_result is not None:
        lines.append("```json")
        lines.append(_safe_json(analysis_result)[:2000])
        lines.append("```")
    elif analysis.strip():
        lines.append("```")
        lines.append(str(analysis)[:2000])
        lines.append("```")
    else:
        lines.append("No analysis output was produced.")
    lines.append("")
    if payload.get("charts"):
        count = len(payload["charts"])
        lines.append(f"Charts generated: {count} PNG artifact(s) embedded in response.")

    lines.extend(["", "## Conclusions"])
    lines.append(
        "The request was processed by the full multi-agent pipeline "
        "(plan -> research -> analysis -> writer/critique). Re-run with "
        "OPENAI_API_KEY and TAVILY_API_KEY configured for LLM-generated reports."
    )
    lines.extend(["", "## References"])
    if sources:
        for src in sources[:25]:
            lines.append(f"- {str(src)[:300]}")
    else:
        lines.append("- No external sources were retrieved.")
    return "\n".join(lines)


def _safe_json(value) -> str:
    try:
        import json

        return json.dumps(value, indent=2, ensure_ascii=False, default=str)
    except Exception:  # noqa: BLE001
        return str(value)


def write_report(payload: dict) -> str:
    """Produce a new draft (agents use latest state at time of call)."""
    settings = get_settings()
    model = get_chat_model()
    max_words = settings.report_max_words

    context = {
        "user_request": payload["user_request"],
        "research_results": payload.get("research_results") or [],
        "research_sources": payload.get("research_sources") or [],
        "analysis_output": payload.get("analysis_output") or "",
        "analysis_result": payload.get("analysis_result"),
        "charts_count": len(payload.get("charts") or []),
    }
    if model is not None:
        try:
            draft = model.invoke(
                [
                    SystemMessage(content=WRITER_SYSTEM),
                    HumanMessage(
                        content=(
                            f"Original request:\n{payload['user_request']}\n\n"
                            f"Word budget: {max_words} words.\n\n"
                            "Research findings:\n"
                            + "\n\n".join(str(r) for r in context["research_results"])
                            + "\n\nData analysis:\n"
                            + str(context["analysis_output"])
                            + "\n\nSources:\n"
                            + "\n".join(f"- {s}" for s in context["research_sources"])
                        )
                    ),
                ]
            )
            text = str(draft.content or "").strip()
            if text:
                return text
        except Exception:  # noqa: BLE001
            pass
    return _fallback_report(context)
